### ISSUE TITLE
Infinite random variates

### ISSUE THREAD

**Issue by mchitre** [org-arl/AlphaStableDistributions.jl#52]
`rand(SymmetricAlphaStable(1.75, 1f0, 0f0))` sometimes generates infinite return value.

**Comment by ymtoo** [comment]
I couldn't reproduce the error using
```julia
for _ ∈ 1:1000000000
  rand(SymmetricAlphaStable(1.75f0, 1f0, 0f0))
end
```
It runs without returning an infinite value on my machine.
```julia
julia> versioninfo()
Julia Version 1.11.2
Commit 5e9a32e7af2 (2024-12-01 20:02 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

Do you have an MWE that can reproduce this error?

**Comment by ymtoo** [comment]
To simulate [`w`](https://github.com/org-arl/AlphaStableDistributions.jl/blob/6776f1aff32c431c9079ae55d8b34f7e0e9e29eb/src/AlphaStableDistributions.jl#L303), which is an independent exponential random variable with mean 1 (https://en.wikipedia.org/wiki/Stable_distribution#Simulation_of_stable_variates), `x=rand(rng, T)` is used to produce $x\in[0,1)$. This is not correct as $x$ should be uniform on $(0, 1)$.

When `x=0`, `w=-log(0)=Inf` and `(cos((one(T)-α)*ϕ) / w)^(one(T)/α - one(T))` yields `Inf` since `(one(T)/α - one(T))` is a negative value.
